//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiduInterop.Interactive {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaiduInterop.Interactive.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 == EOF == 的本地化字符串。
        /// </summary>
        internal static string EnumerableViewEOF {
            get {
                return ResourceManager.GetString("EnumerableViewEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已显示：{0}项。操作：[空格]下一页 [回车]下一项 [Esc]返回 [→]选择项目 的本地化字符串。
        /// </summary>
        internal static string EnumerableViewNavigator {
            get {
                return ResourceManager.GetString("EnumerableViewNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 贴吧名称 的本地化字符串。
        /// </summary>
        internal static string InputForumName {
            get {
                return ResourceManager.GetString("InputForumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效输入。 的本地化字符串。
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列出主题 的本地化字符串。
        /// </summary>
        internal static string ListTopics {
            get {
                return ResourceManager.GetString("ListTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值越界。 的本地化字符串。
        /// </summary>
        internal static string NumberOverflow {
            get {
                return ResourceManager.GetString("NumberOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束 的本地化字符串。
        /// </summary>
        internal static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后…… 的本地化字符串。
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请按任意键继续。 的本地化字符串。
        /// </summary>
        internal static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择操作 的本地化字符串。
        /// </summary>
        internal static string SelectAnOperation {
            get {
                return ResourceManager.GetString("SelectAnOperation", resourceCulture);
            }
        }
    }
}
